FORMAT: 1A
HOST: http://www.vungle.com/api/v1

# Mobile API
The Mobile API gives the Vungle SDKs access to the Vungle Ad Server for serving all of Vungle"s Ads.

# Group Requesting SDK Configuration Settings
## Requesting SDK Config[/config]

### Requesting SDK Config [POST]
+ Request (application/json)
    
        { 
            pubAppId: "VungleApp"
        }


+ Response 200 (application/json)

        { 
            optIn: true,
            threshold: 500,
            updateDelay: 3600,
            connection: 'wifi'
        }