FORMAT: 1A
HOST: http://www.vungle.com/api/v1

# Mobile API
The Mobile API gives the Vungle SDKs access to the Vungle Ad Server for serving all of Vungle"s Ads.

# Group Requesting Ads
## Requesting an Ad [/requestAd]

### Requesting an Ad [POST]
+ Request (application/json)
    
        { 
            pubAppId: "VungleApp", 
            isu: 123456,
            deviceInfo: 
            {
                osVersion: 3.2,
                platform: "iOS",
                dim: 
                {
                    width: 480,
                    height: 320
                }
            }
        }


+ Response 200 (application/json)

        { 
            videoWidth: 480,
            videoHeight: 320,
            url: "http://cds.g8j8b9g6.hwcdn.net/zen/sounfixpromo-480x320-Q2.mp4",
            size: 1211293,
            showClose: 4,
            postBundle: "http://cds.g8j8b9g6.hwcdn.net/bundles/4f46ecbe3d7e73055e0001fa-4.zip",
            md5: "421c55283329e6c4446edb75bd49d589",
            delay: 3,
            cta_overlay:
            {     
                enabled: false,
                show_onclick: true,
                time_show: 5,
                time_enabled: 10,
                click_area: 1.2 
            },
            countdown: 4,
            campaign: "cf630b31bbec9039199aca5f|a8d4cc79ad977810b9d9388a|test",
            callToActionUrl: "http://itunes.apple.com/us/app/feed-the-rat/id531867069?mt=8",
            tpat:
            {
                play_percentage:
                {
                    [
                        checkpoint: .25, 
                        urls: 
                        [
                            "http://trackingurl.com", 
                            "http://trackingurl2.com"
                        ]
                    ],
                },
                mute: 
                [
                    "http://trackingurl.com"
                ],
                unmute: 
                [
                    "http://trackingurl.com", 
                    "http://trackingurl2.com"
                ],
                video_click: 
                [
                    "http://trackingurl3.com"
                ],
                video_close: 
                [
                    "http://trackingurl4.com"
                ],
            }, 
            callToActionDest: "http://itunes.apple.com/us/app/feed-the-rat/id531867069?mt=8",
            app_id: "ios_vungle_Test2",
            expiry: 1395964800,
            id: "53348015fca24d672a000007",
            chk: "26d2ce2b58a2d4614271bef25cec4afb",
            retryCount: 3,
            asyncThreshold: 40
        }