FORMAT: 1A
HOST: http://www.vungle.com/api/v1

# Mobile API
The Mobile API gives the Vungle SDKs access to the Vungle Ad Server for serving all of Vungle"s Ads.

# Group Requesting Ads
## Requesting an Ad [/requestAd]
<strong>Sleep Response (SDK) Meanings</strong>
<table width: 100%; margin: 12px 0 0 0; >
    <tbody>
        <tr>
            <td style="width: 25%; vertical-align: top; color: red;">60</td>
            <td>unfilled request</td>
        </tr>
        <tr>
            <td style="width: 25%; vertical-align: top; color: red;">305</td>
            <td>unknown app</td>
        </tr>
        <tr>
            <td style="border-top: 0px;"></td>
            <td style="border-top: 0px;">no app</td>
        </tr>
        <tr>
            <td style="width: 25%; vertical-align: top; color: red;">350</td>
            <td>no active campaigns</td>
        </tr>
        <tr>
            <td style="width: 25%; vertical-align: top; color: red;">1800</td>
            <td>filters eliminated all options</td>
        </tr>
        <tr>
            <td style="width: 25%; vertical-align: top; color: red;">3600</td>
            <td>inactive app</td>
        </tr>
        <tr>
            <td style="width: 25%; vertical-align: top; color: red;">3601</td>
            <td>network mismatch</td>
        </tr>
        <tr>
            <td style="width: 25%; vertical-align: top; color: red;">86400</td>
            <td>cross promotional app</td>
        </tr>
        <tr>
            <td style="width: 25%; vertical-align: top; color: red;">86401</td>
            <td>OS mismatch</td>
        </tr>
        <tr>
            <td style="width: 25%; vertical-align: top; color: red;">172800</td>
            <td>non-publisher app</td>
        </tr>
    </tbody>
</table>
### Requesting an Ad [POST]
+ Request (application/json)
    
        { 
            pubAppId: "VungleApp", 
            isu: 123456,
            deviceInfo: 
            {
                osVersion: 3.2,
                platform: "iOS",
                dim: 
                {
                    width: 480,
                    height: 320
                }
            }
        }


+ Response 200 (application/json)

        { 
            videoWidth: 480,
            videoHeight: 320,
            url: "http://cds.g8j8b9g6.hwcdn.net/zen/sounfixpromo-480x320-Q2.mp4",
            size: 1211293,
            showClose: 4,
            postBundle: "http://cds.g8j8b9g6.hwcdn.net/bundles/4f46ecbe3d7e73055e0001fa-4.zip",
            md5: "421c55283329e6c4446edb75bd49d589",
            delay: 3,
            cta_overlay:
            {     
                enabled: false,
                show_onclick: true,
                time_show: 5,
                time_enabled: 10,
                click_area: 1.2 
            },
            countdown: 4,
            campaign: "cf630b31bbec9039199aca5f|a8d4cc79ad977810b9d9388a|test",
            callToActionUrl: "http://itunes.apple.com/us/app/feed-the-rat/id531867069?mt=8",
            tpat:
            {
                play_percentage:
                {
                    [
                        checkpoint: .25, 
                        urls: 
                        [
                            "http://trackingurl.com", 
                            "http://trackingurl2.com"
                        ]
                    ],
                },
                mute: 
                [
                    "http://trackingurl.com"
                ],
                unmute: 
                [
                    "http://trackingurl.com", 
                    "http://trackingurl2.com"
                ],
                video_click: 
                [
                    "http://trackingurl3.com"
                ],
                video_close: 
                [
                    "http://trackingurl4.com"
                ],
            }, 
            callToActionDest: "http://itunes.apple.com/us/app/feed-the-rat/id531867069?mt=8",
            app_id: "ios_vungle_Test2",
            expiry: 1395964800,
            id: "53348015fca24d672a000007",
            chk: "26d2ce2b58a2d4614271bef25cec4afb",
            retryCount: 3,
            asyncThreshold: 40
        }

+ Response 200 (application/json)
        {

        
        }

## Requesting a Streaming Ad [/requestStreamingAd]

### Requesting a Streaming Ad [POST]
+ Request (application/json)

        { 
            pubAppId: "VungleApp", 
            isu: 123456,
            campaignId: "12ab3d5f"
            deviceInfo: 
            {
                osVersion: 3.2,
                platform: "iOS",
                dim: 
                {
                    width: 480,
                    height: 320
                }
            }
        }


+ Response 200 (application/json)

        {
            id: "533481c9106d238b2a000008",
            campaign: "533481c8106d238b2a000007|5333340b1884e33d25000742|v2-pub-eRPM",
            callToActionUrl: "http://thirdpartystreaming.com/tracking",
            app_id: "STREAM",
            countdown: 4,
            showClose: 9999,
            cta_overlay:
            {
                click_area: 160,
                time_enabled: 1,
                time_show: 1,
                show_onclick: true,
                enabled: true
            },
            expiry: 1398628799,
            delay: 0,
            shouldStream: true,
            url: "http://thirdpartystreaming.com/video.mp4",
            videoWidth: 400,
            videoHeight: 300,
            tpat:
            {
                play_percentage:
                {
                    [
                        checkpoint: .25, 
                        urls: 
                        [
                            "http://trackingurl.com", 
                            "http://trackingurl2.com"
                        ]
                    ],
                },
                mute: 
                [
                    "http://trackingurl.com"
                ],
                unmute: 
                [
                    "http://trackingurl.com", 
                    "http://trackingurl2.com"
                ],
                pause: [],
                resume: [],
                video_click: 
                [
                    "http://trackingurl3.com"
                ],
                video_close: 
                [
                    "http://trackingurl4.com"
                ],
                error: 
                [
                    "http://trackingurlerror.com"
                ]
            }, 
            chk: "592e45a363cab24e15d97da1933f1f7e",
            retryCount: 3,
            asyncThreshold: 40 
        }